services:
  - type: web
    name: affinityteach-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /actuator/health
    healthCheckMethod: GET
    autoDeploy: true